# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3979984a44f20a9d83726c7ae6278879"
name = "helixo-counter"
handle = "helixo-counter"
application_url = "https://outline-trial-firms-accessing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "helixodata.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://outline-trial-firms-accessing.trycloudflare.com/auth/callback",
  "https://outline-trial-firms-accessing.trycloudflare.com/auth/shopify/callback",
  "https://outline-trial-firms-accessing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
